apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "canary-demo.fullname" . }}
  labels:
    {{- include "canary-demo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "canary-demo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "canary-demo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
---
{{ if .Values.canary.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "canary-demo.fullname" . }}-canary
  labels:
    {{- include "canary-demo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.canary.replicaCount }}
  selector:
    matchLabels:
      {{- include "canary-demo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "canary-demo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.canary.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
{{ end }}
